### ISSUE TITLE
Syntax error (-twoway options-)

### ISSUE THREAD

**Issue by d0nghyunkang** [dballaelliott/esplot#15]
Hi Dylan, thanks for compiling a nice package!

I've found an error when I try to specify a title/note of a plot.

For example, the following code produces an error

`esplot outcome, event(dum_edate) title("Event Study")`
`type mismatch
r(109);
`

It works when I remove spaces in the string.
`esplot outcome, event(dum_edate) title("Event_Study")`

This behavior persists across any twoway options (like -note("xxx")-, -xtitle("yyy")-) that includes spaces in strings.

**Comment by dballaelliott** [comment]
Hi, 

Thanks for flagging this issue. I'm having trouble replicating this bug. Can you please share which version of Stata and which operating system you are using? 

If you're able to provide a log file, that will help me get to the bottom of this very quickly! 

`set trace on` 
`log using debug_esplot.log` 
`<your command>`
`log close`

**Comment by d0nghyunkang** [comment]
Hi, it's weird that this bug doesn't appear when I specify -title- with _your example.csv_. Nonetheless, I'm still having this issue with my own data. What I'm doing is an event study of stock returns around some event date. 

I'm uploading the log file (pretty big!). 

What I'm doing, including the log commands, is like this:

`set trace on`
`log using "C:\Users\dhk.fi\Documents\debug_esplot.log", replace`
`esplot abret, event(dum_edate) window(-10 10) title("Some title")`
`log close`

[debug_esplot.log](https://github.com/dballaelliott/esplot/files/6064390/debug_esplot.log)


I'm using Stata/SE 16.1, operating on Windows 10.

**Comment by dballaelliott** [comment]
Thanks for uploading the detailed log! I see what's going on here. 

Can you try updating to the most recent version of the package with 

`ado update esplot, update` 

The log file revealed that this was a tricky old bug that caused some headaches a few months ago, but that should now be patched in the most recent version.

**Comment by d0nghyunkang** [comment]
Great, after doing updating, now it works. thanks!

**Comment by dballaelliott** [comment]
Great! Glad to hear that it's now working!
