### ISSUE TITLE
Build Stata 13 version?

### ISSUE THREAD

**Issue by clukewatson** [dballaelliott/esplot#7]
Howdy,

I was going to try to use your program, but it is not compatible with Stata 13. Is it possible to build it to be backwards compatible? 

Thank you,
Luke

**Comment by dballaelliott** [comment]
Hey there, 

Let me check if there's anything keeping me from rolling it back to Stata 13 - I think it should be pretty close to working as is. It's probably just transparency in the plot that would cause trouble, but I may be to just turn off transparency conditional on version.

**Comment by dballaelliott** [comment]
Ok there is now nominal support through Stata 11; it was able to pass my tests with `version 11` - let me know if it blocks you from running this!

**Comment by clukewatson** [comment]
Everything seem to be working great. I am mostly using for the by() feature.

Thanks for the super fast reply!
